// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shortcut } from "./Shortcut";

/**
 * The first action in a view's list is primary and runs on Enter. Others
 * are reached through the action panel. Each may declare a shortcut.
 */
export type Action = { id: string, title: string, shortcut: Shortcut | null, };
