// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a `no-view` command. On success the launcher hides; on
 * failure it stays open and shows the message.
 */
export type CommandOutcome = { "status": "success", message: string | null, } | { "status": "failure", message: string, };
