// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

export type DetailView = { markdown: string, loading: boolean, actions: Array<Action>, };
