// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who narrows a list as the user types. `Launcher` filters the given items
 * without re-invoking the command; `Command` means the command owns
 * filtering and receives each query change.
 */
export type Filtering = "launcher" | "command";
