// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldKind } from "./FieldKind";

export type FormField = { id: string, label: string, kind: FieldKind, value: string | null, };
