// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { FormField } from "./FormField";

export type FormView = { itemId: string | null, fields: Array<FormField>, actions: Array<Action>, };
