// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmptyState } from "./EmptyState";
import type { Filtering } from "./Filtering";
import type { ListItem } from "./ListItem";

export type ListView = { filtering: Filtering, loading: boolean, emptyState: EmptyState | null, items: Array<ListItem>, };
