// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

export type ListItem = { id: string, title: string, subtitle: string | null, icon: string | null, 
/**
 * The selected item's action panel. The first action is primary.
 */
actions: Array<Action>, };
