// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetailView } from "./DetailView";
import type { FormView } from "./FormView";
import type { ListView } from "./ListView";

export type View = { "kind": "list" } & ListView | { "kind": "detail" } & DetailView | { "kind": "form" } & FormView;
