// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { View } from "./View";

export type ViewTree = { protocolVersion: number, view: View, };
