//! Deciding whether what was just copied should be remembered.
//!
//! The crate says *when* the clipboard changed. Everything here is about
//! whether to look at it, and the order matters: the type list and the
//! attribution are both consulted before a single byte of content is read, so
//! an excluded password never reaches Dango's memory.

use std::collections::VecDeque;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use super::history::{Bounds, Content, History};
use super::source::{Attribution, ClipboardSource};

/// Markers meaning "not for history". Some applications set one; the spike
/// found a mainstream password manager that sets none, so nothing depends on
/// them and they are a bonus over the exclusion list.
const EXCLUDING_MARKERS: &[&str] = &[
    // macOS, by convention rather than by Apple.
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    // Windows.
    "ExcludeClipboardContentFromMonitorProcessing",
    "CanIncludeInClipboardHistory",
];

/// What the watcher needs to know each time the clipboard moves. Read per
/// change rather than at startup, so editing the exclusion list takes effect
/// without a restart.
pub trait Policy: Send + Sync {
    fn bounds(&self) -> Bounds;
    fn excluded_applications(&self) -> Vec<String>;
}

/// A paste declares two writes. A few more than that absorbs an overlapping
/// second insertion without ever growing into a standing rule about content.
const PENDING_OWN_WRITES: usize = 4;

pub struct Watcher {
    source: Arc<dyn ClipboardSource>,
    attribution: Arc<dyn Attribution>,
    history: Arc<History>,
    policy: Arc<dyn Policy>,
    /// What Dango itself just put on the clipboard, which must not come back as
    /// a new entry. One shot and content-matched: a later copy of the same
    /// thing by the user is still theirs.
    ours: Mutex<VecDeque<Content>>,
    running: AtomicBool,
}

impl Watcher {
    pub fn new(
        source: Arc<dyn ClipboardSource>,
        attribution: Arc<dyn Attribution>,
        history: Arc<History>,
        policy: Arc<dyn Policy>,
    ) -> Self {
        Self {
            source,
            attribution,
            history,
            policy,
            ours: Mutex::new(VecDeque::new()),
            running: AtomicBool::new(false),
        }
    }

    pub fn running(&self) -> bool {
        self.running.load(Ordering::SeqCst)
    }

    pub fn start(&self) {
        self.running.store(true, Ordering::SeqCst);
    }

    pub fn stop(&self) {
        self.running.store(false, Ordering::SeqCst);
    }

    /// Puts an entry back on the clipboard, remembering it so the change that
    /// follows is recognised as Dango's own.
    pub fn restore(&self, content: &Content) {
        self.expect_own_write(content);
        match content {
            Content::Text(text) => self.source.set_text(text),
            Content::Image(png) => self.source.set_image(png),
        }
    }

    /// One clipboard change. Answers whether it was recorded, which is what the
    /// tests want to know.
    pub fn handle_change(&self, now: i64) -> bool {
        if !self.running() {
            return false;
        }
        // Both checks run before a single byte of content is read.
        if self.is_marked_excluded() || self.copied_from_excluded_application() {
            return false;
        }
        let Some(content) = self.read() else {
            return false;
        };
        if self.was_ours(&content) {
            return false;
        }
        match self.history.record(content, self.policy.bounds(), now) {
            Ok(()) => true,
            Err(error) => {
                eprintln!("[dango] could not record what was copied: {error}");
                false
            }
        }
    }

    fn is_marked_excluded(&self) -> bool {
        self.source
            .formats()
            .iter()
            .any(|format| EXCLUDING_MARKERS.contains(&format.as_str()))
    }

    /// Any candidate being excluded is enough. Deliberately asymmetric: this
    /// will sometimes decline to record something it could have kept, which is
    /// a nuisance, rather than keep a password, which is a liability.
    fn copied_from_excluded_application(&self) -> bool {
        let excluded = self.policy.excluded_applications();
        if excluded.is_empty() {
            return false;
        }
        self.attribution
            .candidate_applications()
            .iter()
            .any(|name| {
                excluded
                    .iter()
                    .any(|candidate| candidate.eq_ignore_ascii_case(name))
            })
    }

    /// Declares a write Dango is about to make, so the change it causes is not
    /// recorded. A paste makes two: the text going out and the user's own
    /// content going back, which is why this is a queue rather than one slot.
    pub fn expect_own_write(&self, content: &Content) {
        let mut ours = self.ours.lock().unwrap();
        if ours.len() == PENDING_OWN_WRITES {
            ours.pop_front();
        }
        ours.push_back(content.clone());
    }

    /// Matched entries are consumed, so a suppression covers exactly the one
    /// change it was declared for. Everything else is the user's own copy, even
    /// when it happens to hold the same content.
    fn was_ours(&self, content: &Content) -> bool {
        let mut ours = self.ours.lock().unwrap();
        match ours.iter().position(|pending| pending == content) {
            Some(index) => {
                ours.remove(index);
                true
            }
            None => false,
        }
    }

    /// Text first: an application that offers both usually means the text, and
    /// the text is the cheaper thing to keep.
    fn read(&self) -> Option<Content> {
        if let Some(text) = self.source.text().filter(|t| !t.trim().is_empty()) {
            return Some(Content::Text(text));
        }
        self.source.image().map(Content::Image)
    }
}

/// Runs the crate's watcher on its own thread, so nothing it does can touch the
/// activation path. Stops when the extension is disabled.
pub struct WatchService {
    watcher: Arc<Watcher>,
}

impl WatchService {
    pub fn new(watcher: Arc<Watcher>) -> Self {
        Self { watcher }
    }
}

struct Handler(Arc<Watcher>);

impl clipboard_rs::ClipboardHandler for Handler {
    fn on_clipboard_change(&mut self) {
        self.0.attribution.wait_for_copy_to_finish();
        self.0.handle_change(crate::ranking::now_millis());
    }
}

impl crate::extension::Service for WatchService {
    fn start(&self) -> crate::extension::ActivationResult {
        use clipboard_rs::ClipboardWatcher;

        self.watcher.start();
        let watcher = self.watcher.clone();
        std::thread::spawn(move || {
            let mut context = match clipboard_rs::ClipboardWatcherContext::new() {
                Ok(context) => context,
                Err(error) => {
                    eprintln!("[dango] could not watch the clipboard: {error}");
                    return;
                }
            };
            let shutdown = context
                .add_handler(Handler(watcher.clone()))
                .get_shutdown_channel();

            // The crate's watch loop blocks, so stopping is a second thread
            // waiting on the flag the extension clears when it is disabled.
            std::thread::spawn(move || {
                while watcher.running() {
                    std::thread::sleep(std::time::Duration::from_millis(200));
                }
                shutdown.stop();
            });

            context.start_watch();
        });
        Ok(())
    }

    fn stop(&self) {
        self.watcher.stop();
    }
}

/// The clipboard history's side of the bargain with the selection and paste
/// path: whatever that borrows, the history never sees.
impl crate::text::OwnWrites for Watcher {
    fn expect(&self, content: &Content) {
        self.expect_own_write(content);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Default)]
    struct FakeClipboard {
        formats: Mutex<Vec<String>>,
        text: Mutex<Option<String>>,
        image: Mutex<Option<Vec<u8>>>,
        /// Every read of content, so a test can prove excluded content was
        /// never looked at.
        reads: Mutex<Vec<&'static str>>,
    }

    impl FakeClipboard {
        fn copy_text(&self, value: &str) {
            *self.text.lock().unwrap() = Some(value.into());
            *self.image.lock().unwrap() = None;
            *self.formats.lock().unwrap() = vec!["public.utf8-plain-text".into()];
        }

        fn copy_image(&self, bytes: &[u8]) {
            *self.text.lock().unwrap() = None;
            *self.image.lock().unwrap() = Some(bytes.to_vec());
            *self.formats.lock().unwrap() = vec!["public.png".into()];
        }

        fn mark_excluded(&self) {
            self.formats
                .lock()
                .unwrap()
                .push("org.nspasteboard.ConcealedType".into());
        }
    }

    impl ClipboardSource for FakeClipboard {
        fn formats(&self) -> Vec<String> {
            self.formats.lock().unwrap().clone()
        }
        fn text(&self) -> Option<String> {
            self.reads.lock().unwrap().push("text");
            self.text.lock().unwrap().clone()
        }
        fn image(&self) -> Option<Vec<u8>> {
            self.reads.lock().unwrap().push("image");
            self.image.lock().unwrap().clone()
        }
        fn set_text(&self, value: &str) {
            self.copy_text(value);
        }
        fn set_image(&self, png: &[u8]) {
            self.copy_image(png);
        }
    }

    #[derive(Default)]
    struct FakeAttribution(Mutex<Vec<String>>);

    impl FakeAttribution {
        fn from(&self, application: &str) {
            *self.0.lock().unwrap() = vec![application.into()];
        }

        /// The user copied in one application and switched to another before
        /// the change was noticed, so both are candidates.
        fn copied_in_then_switched_to(&self, copied_in: &str, switched_to: &str) {
            *self.0.lock().unwrap() = vec![copied_in.into(), switched_to.into()];
        }
    }

    impl Attribution for FakeAttribution {
        fn candidate_applications(&self) -> Vec<String> {
            self.0.lock().unwrap().clone()
        }
    }

    #[derive(Default)]
    struct FakePolicy {
        excluded: Mutex<Vec<String>>,
        bounds: Mutex<Bounds>,
    }

    impl Policy for FakePolicy {
        fn bounds(&self) -> Bounds {
            *self.bounds.lock().unwrap()
        }
        fn excluded_applications(&self) -> Vec<String> {
            self.excluded.lock().unwrap().clone()
        }
    }

    struct Fixture {
        clipboard: Arc<FakeClipboard>,
        attribution: Arc<FakeAttribution>,
        policy: Arc<FakePolicy>,
        history: Arc<History>,
        watcher: Watcher,
    }

    fn setup() -> Fixture {
        let clipboard = Arc::new(FakeClipboard::default());
        let attribution = Arc::new(FakeAttribution::default());
        let policy = Arc::new(FakePolicy::default());
        let dir = std::env::temp_dir().join(format!("dango-watch-{}", uuid::Uuid::new_v4()));
        let history = Arc::new(History::new(
            Arc::new(crate::store::Store::in_memory().unwrap()),
            dir,
        ));
        let watcher = Watcher::new(
            clipboard.clone(),
            attribution.clone(),
            history.clone(),
            policy.clone(),
        );
        watcher.start();
        Fixture {
            clipboard,
            attribution,
            policy,
            history,
            watcher,
        }
    }

    fn texts(history: &History) -> Vec<String> {
        history
            .entries()
            .unwrap()
            .into_iter()
            .filter_map(|e| e.text)
            .collect()
    }

    #[test]
    fn a_copy_is_recorded() {
        let f = setup();
        f.clipboard.copy_text("hello");
        assert!(f.watcher.handle_change(1));
        assert_eq!(texts(&f.history), ["hello"]);
    }

    #[test]
    fn an_image_is_recorded() {
        let f = setup();
        f.clipboard.copy_image(&[1, 2, 3]);
        assert!(f.watcher.handle_change(1));
        assert_eq!(
            f.history.entries().unwrap()[0].kind,
            super::super::Kind::Image
        );
    }

    #[test]
    fn marked_content_is_never_even_read() {
        let f = setup();
        f.clipboard.copy_text("a password");
        f.clipboard.mark_excluded();

        assert!(!f.watcher.handle_change(1));
        assert!(f.history.entries().unwrap().is_empty());
        assert!(
            f.clipboard.reads.lock().unwrap().is_empty(),
            "excluded content must not reach Dango's memory at all"
        );
    }

    #[test]
    fn content_from_an_excluded_application_is_never_even_read() {
        let f = setup();
        f.policy.excluded.lock().unwrap().push("Proton Pass".into());
        f.attribution.from("Proton Pass");
        f.clipboard.copy_text("a password");

        assert!(!f.watcher.handle_change(1));
        assert!(f.history.entries().unwrap().is_empty());
        assert!(f.clipboard.reads.lock().unwrap().is_empty());
    }

    /// The case the macOS spike exposed: a password copied from a manager the
    /// user leaves immediately.
    #[test]
    fn an_excluded_application_left_before_the_copy_was_noticed_still_excludes() {
        let f = setup();
        f.policy.excluded.lock().unwrap().push("Proton Pass".into());
        f.attribution
            .copied_in_then_switched_to("Proton Pass", "Ghostty");
        f.clipboard.copy_text("a password");

        assert!(!f.watcher.handle_change(1));
        assert!(f.clipboard.reads.lock().unwrap().is_empty());
    }

    #[test]
    fn switching_between_two_allowed_applications_still_records() {
        let f = setup();
        f.policy.excluded.lock().unwrap().push("Proton Pass".into());
        f.attribution.copied_in_then_switched_to("Notes", "Ghostty");
        f.clipboard.copy_text("something ordinary");

        assert!(f.watcher.handle_change(1));
        assert_eq!(texts(&f.history), ["something ordinary"]);
    }

    #[test]
    fn the_exclusion_list_is_read_per_change_not_at_startup() {
        let f = setup();
        f.attribution.from("Notes");
        f.clipboard.copy_text("first");
        assert!(f.watcher.handle_change(1));

        f.policy.excluded.lock().unwrap().push("Notes".into());
        f.clipboard.copy_text("second");
        assert!(!f.watcher.handle_change(2));

        assert_eq!(texts(&f.history), ["first"]);
    }

    #[test]
    fn an_application_name_is_matched_regardless_of_case() {
        let f = setup();
        f.policy.excluded.lock().unwrap().push("1password".into());
        f.attribution.from("1Password");
        f.clipboard.copy_text("a password");
        assert!(!f.watcher.handle_change(1));
    }

    #[test]
    fn dangos_own_write_is_not_recorded() {
        let f = setup();
        f.clipboard.copy_text("hello");
        assert!(f.watcher.handle_change(1));

        f.watcher.restore(&Content::Text("hello".into()));
        assert!(
            !f.watcher.handle_change(2),
            "putting an entry back must not create another entry"
        );
        assert_eq!(f.history.entries().unwrap().len(), 1);
    }

    #[test]
    fn only_the_one_change_a_restore_caused_is_suppressed() {
        let f = setup();
        f.watcher.restore(&Content::Text("hello".into()));
        assert!(!f.watcher.handle_change(1));

        // The user copies it again from somewhere else.
        f.clipboard.copy_text("hello");
        assert!(
            f.watcher.handle_change(2),
            "the suppression is one shot, not a standing rule about the content"
        );
    }

    #[test]
    fn both_writes_of_a_paste_are_suppressed() {
        let f = setup();
        f.clipboard.copy_text("what the user had");
        assert!(f.watcher.handle_change(1));

        // An insertion borrows the clipboard: the text goes out, then the
        // user's own content goes back.
        f.watcher
            .expect_own_write(&Content::Text("the snippet".into()));
        f.watcher
            .expect_own_write(&Content::Text("what the user had".into()));

        f.clipboard.copy_text("the snippet");
        assert!(!f.watcher.handle_change(2), "the pasted text is not a copy");
        f.clipboard.copy_text("what the user had");
        assert!(
            !f.watcher.handle_change(3),
            "restoring the user's clipboard is not a copy either"
        );
        assert_eq!(
            f.history.entries().unwrap().len(),
            1,
            "the history is untouched by a paste"
        );
    }

    #[test]
    fn restoring_the_clipboard_does_not_reorder_the_history() {
        let f = setup();
        f.clipboard.copy_text("older");
        f.watcher.handle_change(1);
        f.clipboard.copy_text("newer");
        f.watcher.handle_change(2);

        let before: Vec<_> = f
            .history
            .entries()
            .unwrap()
            .into_iter()
            .map(|entry| entry.id)
            .collect();

        // Pasting the older entry puts it out and then puts "newer" back.
        f.watcher.expect_own_write(&Content::Text("older".into()));
        f.watcher.expect_own_write(&Content::Text("newer".into()));
        f.clipboard.copy_text("older");
        f.watcher.handle_change(3);
        f.clipboard.copy_text("newer");
        f.watcher.handle_change(4);

        let after: Vec<_> = f
            .history
            .entries()
            .unwrap()
            .into_iter()
            .map(|entry| entry.id)
            .collect();
        assert_eq!(before, after, "a paste must not reorder what the user has");
    }

    #[test]
    fn a_genuine_copy_during_a_paste_is_still_recorded() {
        let f = setup();
        f.watcher
            .expect_own_write(&Content::Text("the snippet".into()));
        f.watcher
            .expect_own_write(&Content::Text("what the user had".into()));

        f.clipboard.copy_text("something the user copied");
        assert!(
            f.watcher.handle_change(1),
            "the queue suppresses declared content, not a window of time"
        );
    }

    #[test]
    fn a_copy_that_is_not_what_we_restored_still_counts() {
        let f = setup();
        f.watcher.restore(&Content::Text("ours".into()));
        f.clipboard.copy_text("theirs");
        assert!(
            f.watcher.handle_change(1),
            "a restore must not swallow whatever the user copied next"
        );
        assert_eq!(texts(&f.history), ["theirs"]);
    }

    #[test]
    fn whitespace_only_text_is_not_worth_keeping() {
        let f = setup();
        f.clipboard.copy_text("   \n  ");
        assert!(!f.watcher.handle_change(1));
        assert!(f.history.entries().unwrap().is_empty());
    }

    #[test]
    fn a_stopped_watcher_records_nothing() {
        let f = setup();
        f.watcher.stop();
        f.clipboard.copy_text("while stopped");
        assert!(!f.watcher.handle_change(1));
        assert!(f.history.entries().unwrap().is_empty());
    }
}
