//! The view protocol: the versioned, declarative description of what a command
//! puts on screen. Rust is the source of truth; the matching TypeScript in
//! `src/protocol/` is generated by ts-rs during `cargo test` and checked in, so
//! CI fails if the two drift. ts-rs is a dev dependency and the derives are
//! gated to test builds, keeping it out of the release binary.

use serde::{Deserialize, Serialize};

#[cfg(test)]
use ts_rs::TS;

/// Bumped when the protocol changes shape. The frontend refuses a tree whose
/// version it does not recognise.
pub const PROTOCOL_VERSION: u32 = 1;

/// Event carrying a full view tree from a command to the frontend. Updates are
/// whole-tree replacements, never patches.
pub const EVENT_RENDER: &str = "dango://render";

macro_rules! protocol_types {
    ($($item:item)*) => {
        $(
            #[cfg_attr(test, derive(TS))]
            #[cfg_attr(test, ts(export, export_to = "../../src/protocol/"))]
            #[derive(Clone, Debug, Serialize, Deserialize)]
            $item
        )*
    };
}

protocol_types! {
    #[serde(rename_all = "camelCase")]
    pub struct ViewTree {
        pub protocol_version: u32,
        pub view: View,
    }

    #[serde(tag = "kind", rename_all = "camelCase")]
    pub enum View {
        List(ListView),
        Detail(DetailView),
        Form(FormView),
    }

    #[serde(rename_all = "camelCase")]
    pub struct ListView {
        pub filtering: Filtering,
        #[serde(default)]
        pub loading: bool,
        #[serde(default)]
        pub empty_state: Option<EmptyState>,
        pub items: Vec<ListItem>,
    }

    /// Who narrows a list as the user types. `Launcher` filters the given items
    /// without re-invoking the command; `Command` means the command owns
    /// filtering and receives each query change.
    #[serde(rename_all = "camelCase")]
    pub enum Filtering {
        Launcher,
        Command,
    }

    #[serde(rename_all = "camelCase")]
    pub struct ListItem {
        pub id: String,
        pub title: String,
        #[serde(default)]
        pub subtitle: Option<String>,
        #[serde(default)]
        pub icon: Option<String>,
        /// The selected item's action panel. The first action is primary.
        #[serde(default)]
        pub actions: Vec<Action>,
    }

    #[serde(rename_all = "camelCase")]
    pub struct DetailView {
        pub markdown: String,
        #[serde(default)]
        pub loading: bool,
        #[serde(default)]
        pub actions: Vec<Action>,
    }

    #[serde(rename_all = "camelCase")]
    pub struct FormView {
        pub fields: Vec<FormField>,
        #[serde(default)]
        pub actions: Vec<Action>,
    }

    #[serde(rename_all = "camelCase")]
    pub struct FormField {
        pub id: String,
        pub label: String,
        pub kind: FieldKind,
        #[serde(default)]
        pub value: Option<String>,
    }

    #[serde(rename_all = "camelCase")]
    pub enum FieldKind {
        Text,
        Password,
        Toggle,
    }

    #[serde(rename_all = "camelCase")]
    pub struct EmptyState {
        pub title: String,
        #[serde(default)]
        pub description: Option<String>,
    }

    /// The first action in a view's list is primary and runs on Enter. Others
    /// are reached through the action panel. Each may declare a shortcut.
    #[serde(rename_all = "camelCase")]
    pub struct Action {
        pub id: String,
        pub title: String,
        #[serde(default)]
        pub shortcut: Option<Shortcut>,
    }

    #[serde(rename_all = "camelCase")]
    pub struct Shortcut {
        pub key: String,
        #[serde(default)]
        pub modifiers: Vec<Modifier>,
    }

    #[serde(rename_all = "camelCase")]
    pub enum Modifier {
        Cmd,
        Ctrl,
        Alt,
        Shift,
    }

    /// The result of a `no-view` command. On success the launcher hides; on
    /// failure it stays open and shows the message.
    #[serde(tag = "status", rename_all = "camelCase")]
    pub enum CommandOutcome {
        Success {
            #[serde(default)]
            message: Option<String>,
        },
        Failure {
            message: String,
        },
    }
}

impl ViewTree {
    pub fn new(view: View) -> Self {
        Self {
            protocol_version: PROTOCOL_VERSION,
            view,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_list_tree_round_trips_through_json() {
        let tree = ViewTree::new(View::List(ListView {
            filtering: Filtering::Launcher,
            loading: false,
            empty_state: Some(EmptyState {
                title: "No results".into(),
                description: None,
            }),
            items: vec![ListItem {
                id: "apps.open".into(),
                title: "Open".into(),
                subtitle: None,
                icon: None,
                actions: vec![Action {
                    id: "launch".into(),
                    title: "Launch".into(),
                    shortcut: None,
                }],
            }],
        }));
        let json = serde_json::to_string(&tree).unwrap();
        assert!(json.contains("\"protocolVersion\":1"));
        assert!(json.contains("\"kind\":\"list\""));
        assert!(json.contains("\"filtering\":\"launcher\""));
        let back: ViewTree = serde_json::from_str(&json).unwrap();
        assert!(matches!(back.view, View::List(_)));
    }

    #[test]
    fn a_no_view_outcome_carries_its_status() {
        let json = serde_json::to_string(&CommandOutcome::Failure {
            message: "no such app".into(),
        })
        .unwrap();
        assert!(json.contains("\"status\":\"failure\""));
    }
}
