//! The macOS clipboard, and the trail of who might have written to it.
//!
//! The spike is why this is more than a few pasteboard calls. Proton Pass sets
//! no privacy marker, and asking which application is frontmost at the moment a
//! change is noticed blamed a password on the terminal the user had switched
//! back to. So activations are recorded as they happen, and a change is
//! attributed to everything that was frontmost around it.

use std::ptr::NonNull;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use block2::RcBlock;
use objc2_app_kit::{
    NSPasteboard, NSPasteboardTypePNG, NSPasteboardTypeString, NSPasteboardTypeTIFF, NSWorkspace,
    NSWorkspaceDidActivateApplicationNotification,
};
use objc2_foundation::{NSData, NSNotification, NSString};

use crate::extensions::clipboard::ClipboardSource;

/// The convention some password managers follow. Not an Apple constant, and the
/// spike found a mainstream manager that sets neither, so nothing depends on
/// these; they are a bonus on top of the exclusion list.
const CONCEALED: &str = "org.nspasteboard.ConcealedType";
const AUTO_GENERATED: &str = "org.nspasteboard.AutoGeneratedType";

/// How far back an activation still counts as a candidate for a change noticed
/// now. Wider than the poll interval, because the change happened somewhere
/// inside the interval and the switch away may have preceded noticing it.
const TRAIL_WINDOW: Duration = Duration::from_millis(1_500);

/// How many activations to remember. A handful covers any plausible flurry of
/// switching, and the trail is walked on every clipboard change.
const TRAIL_LENGTH: usize = 8;

/// Shared with the activation observer, which outlives any particular caller.
type Trail = Arc<Mutex<Vec<(String, Instant)>>>;

pub struct MacClipboard {
    trail: Trail,
}

impl Default for MacClipboard {
    fn default() -> Self {
        Self::new()
    }
}

impl MacClipboard {
    pub fn new() -> Self {
        Self {
            trail: Arc::new(Mutex::new(Vec::new())),
        }
    }

    /// Starts recording activations. Separate from construction because it
    /// needs the application's run loop, which is running by the time an
    /// extension activates but not necessarily when it is built.
    ///
    /// Must be called from the main thread: `NSWorkspace`'s notification centre
    /// is not thread-safe to register with, and with no queue the block is
    /// delivered on the thread that posts, which is the main one.
    pub fn watch_activations(&self) {
        let trail = self.trail.clone();
        let handler = RcBlock::new(move |_: NonNull<NSNotification>| {
            if let Some(name) = frontmost_name() {
                remember(&trail, name);
            }
        });
        let observer = unsafe {
            NSWorkspace::sharedWorkspace()
                .notificationCenter()
                .addObserverForName_object_queue_usingBlock(
                    Some(NSWorkspaceDidActivateApplicationNotification),
                    None,
                    None,
                    &handler,
                )
        };
        // Deliberately leaked. Dropping the observer unregisters it, and a
        // trail that quietly stops being fed stops excluding anything, which is
        // the one failure here that costs a password. It is one object for the
        // life of the process.
        std::mem::forget(observer);
    }
}

fn remember(trail: &Mutex<Vec<(String, Instant)>>, name: String) {
    let mut trail = trail.lock().unwrap();
    if trail.last().is_some_and(|(last, _)| *last == name) {
        return;
    }
    trail.push((name, Instant::now()));
    let excess = trail.len().saturating_sub(TRAIL_LENGTH);
    trail.drain(..excess);
}

fn frontmost_name() -> Option<String> {
    NSWorkspace::sharedWorkspace()
        .frontmostApplication()
        .and_then(|app| app.localizedName())
        .map(|name| name.to_string())
}

impl ClipboardSource for MacClipboard {
    fn sequence(&self) -> i64 {
        NSPasteboard::generalPasteboard().changeCount() as i64
    }

    fn is_excluded(&self) -> bool {
        types()
            .iter()
            .any(|t| t == CONCEALED || t == AUTO_GENERATED)
    }

    fn candidate_applications(&self) -> Vec<String> {
        let mut candidates: Vec<String> = self
            .trail
            .lock()
            .unwrap()
            .iter()
            .filter(|(_, at)| at.elapsed() <= TRAIL_WINDOW)
            .map(|(name, _)| name.clone())
            .collect();
        // Whoever is frontmost now is always a candidate, which is what makes
        // this work before any activation has been seen.
        if let Some(name) = frontmost_name() {
            if !candidates.contains(&name) {
                candidates.push(name);
            }
        }
        candidates
    }

    fn text(&self) -> Option<String> {
        let value =
            unsafe { NSPasteboard::generalPasteboard().stringForType(NSPasteboardTypeString) }?;
        Some(value.to_string())
    }

    /// PNG in preference to TIFF: the spike measured the same image at 1,571
    /// bytes of PNG against 37,482 of TIFF, and the history is size-bounded.
    fn image(&self) -> Option<Vec<u8>> {
        let pasteboard = NSPasteboard::generalPasteboard();
        if let Some(png) = unsafe { pasteboard.dataForType(NSPasteboardTypePNG) } {
            return Some(png.to_vec());
        }
        let tiff = unsafe { pasteboard.dataForType(NSPasteboardTypeTIFF) }?;
        to_png(&tiff)
    }

    fn set_text(&self, text: &str) {
        let pasteboard = NSPasteboard::generalPasteboard();
        pasteboard.clearContents();
        unsafe {
            pasteboard.setString_forType(&NSString::from_str(text), NSPasteboardTypeString);
        }
    }

    fn set_image(&self, png: &[u8]) {
        let pasteboard = NSPasteboard::generalPasteboard();
        pasteboard.clearContents();
        unsafe {
            pasteboard.setData_forType(Some(&NSData::with_bytes(png)), NSPasteboardTypePNG);
        }
    }
}

fn types() -> Vec<String> {
    NSPasteboard::generalPasteboard()
        .types()
        .map(|list| list.iter().map(|t| t.to_string()).collect())
        .unwrap_or_default()
}

/// An application that offers only TIFF still has to be storable as PNG, since
/// that is the one encoding the history and the webview agree on.
fn to_png(tiff: &NSData) -> Option<Vec<u8>> {
    use objc2_app_kit::{NSBitmapImageFileType, NSBitmapImageRep};
    use objc2_foundation::NSDictionary;

    let rep = NSBitmapImageRep::imageRepWithData(tiff)?;
    let data = unsafe {
        rep.representationUsingType_properties(NSBitmapImageFileType::PNG, &NSDictionary::new())
    }?;
    Some(data.to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_trail_keeps_the_most_recent_activations() {
        let trail: Trail = Arc::new(Mutex::new(Vec::new()));
        for index in 0..TRAIL_LENGTH + 4 {
            remember(&trail, format!("app {index}"));
        }
        let kept = trail.lock().unwrap();
        assert_eq!(kept.len(), TRAIL_LENGTH);
        assert_eq!(kept.last().unwrap().0, format!("app {}", TRAIL_LENGTH + 3));
    }

    #[test]
    fn reactivating_the_same_application_does_not_fill_the_trail() {
        let trail: Trail = Arc::new(Mutex::new(Vec::new()));
        remember(&trail, "Ghostty".into());
        remember(&trail, "Ghostty".into());
        remember(&trail, "Ghostty".into());
        assert_eq!(trail.lock().unwrap().len(), 1);
    }

    #[test]
    fn the_window_is_wider_than_the_poll_interval() {
        assert!(
            TRAIL_WINDOW > crate::extensions::clipboard::POLL_INTERVAL,
            "a change is noticed up to a poll late, so the trail has to reach back further"
        );
    }

    /// Needs a window server and a pasteboard: run on a real desktop with
    /// `cargo test -- --ignored`.
    mod live {
        use super::*;

        #[test]
        #[ignore]
        fn text_survives_a_round_trip() {
            let clipboard = MacClipboard::new();
            let before = clipboard.sequence();
            clipboard.set_text("dango round trip");
            assert_eq!(clipboard.text().as_deref(), Some("dango round trip"));
            assert!(
                clipboard.sequence() > before,
                "writing must move the counter"
            );
        }

        #[test]
        #[ignore]
        fn an_image_survives_a_round_trip_as_png() {
            let png = std::fs::read(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../static/favicon.png"
            ))
            .unwrap();
            let clipboard = MacClipboard::new();
            clipboard.set_image(&png);

            let read = clipboard.image().expect("an image must come back");
            assert_eq!(read, png, "PNG is offered and read without re-encoding");
            assert!(clipboard.text().is_none(), "an image is not text");
        }

        #[test]
        #[ignore]
        fn whoever_is_frontmost_is_always_a_candidate() {
            let clipboard = MacClipboard::new();
            assert!(
                !clipboard.candidate_applications().is_empty(),
                "something is always frontmost on a real desktop"
            );
        }

        #[test]
        #[ignore]
        fn ordinary_text_carries_no_privacy_marker() {
            let clipboard = MacClipboard::new();
            clipboard.set_text("nothing secret");
            assert!(!clipboard.is_excluded());
        }
    }
}
