//! M2 spike: what macOS will tell us about the clipboard, and how fast.
//!
//! Answers tasks 1.1, 1.3, 1.5, and 1.6 before the macOS `ClipboardSource` is
//! built on assumptions. Run it, then copy things: ordinary text, an image, and
//! something from a password manager.
//!
//! Usage: `cargo run --example clipboard_spike`

#[cfg(not(target_os = "macos"))]
fn main() {
    eprintln!("clipboard_spike only runs on macOS");
}

#[cfg(target_os = "macos")]
fn main() {
    spike::run();
}

#[cfg(target_os = "macos")]
mod spike {
    use std::time::{Duration, Instant};

    use objc2_app_kit::{
        NSPasteboard, NSPasteboardTypePNG, NSPasteboardTypeString, NSPasteboardTypeTIFF,
        NSWorkspace,
    };
    use objc2_foundation::NSString;

    /// The convention password managers follow. Not an Apple constant, which is
    /// itself worth confirming rather than assuming.
    const CONCEALED: &str = "org.nspasteboard.ConcealedType";
    const AUTO_GENERATED: &str = "org.nspasteboard.AutoGeneratedType";

    const POLL: Duration = Duration::from_millis(250);

    pub fn run() {
        let pasteboard = NSPasteboard::generalPasteboard();
        let mut last = pasteboard.changeCount();
        let mut changes = 0;

        println!("watching the clipboard, ctrl-c to stop");
        println!("copy: some text, an image, then something from a password manager\n");
        println!("starting change count: {last}\n");

        loop {
            std::thread::sleep(POLL);
            let now = pasteboard.changeCount();
            if now == last {
                continue;
            }
            changes += 1;
            let jumped = now - last;
            last = now;

            // Everything below mirrors the order the real watcher will use:
            // types first, then the markers, then content only if allowed.
            let started = Instant::now();
            let types: Vec<String> = pasteboard
                .types()
                .map(|list| list.iter().map(|t| t.to_string()).collect())
                .unwrap_or_default();
            let types_took = started.elapsed();

            let concealed = types.iter().any(|t| t == CONCEALED);
            let auto = types.iter().any(|t| t == AUTO_GENERATED);
            let frontmost = NSWorkspace::sharedWorkspace()
                .frontmostApplication()
                .and_then(|app| app.localizedName())
                .map(|name| name.to_string())
                .unwrap_or_else(|| "unknown".into());

            println!("change {changes}: count {now} (+{jumped}), frontmost {frontmost:?}");
            println!("  types ({:?}): {}", types_took, summarise(&types));

            if concealed || auto {
                println!(
                    "  EXCLUDED: concealed={concealed} auto-generated={auto}; reading nothing\n"
                );
                continue;
            }

            let started = Instant::now();
            let text = unsafe { pasteboard.stringForType(NSPasteboardTypeString) }
                .map(|value| value.to_string());
            let text_took = started.elapsed();

            let started = Instant::now();
            let png = read_bytes(&pasteboard, unsafe { NSPasteboardTypePNG });
            let tiff = read_bytes(&pasteboard, unsafe { NSPasteboardTypeTIFF });
            let image_took = started.elapsed();

            match &text {
                Some(value) => println!("  text ({text_took:?}): {:?}", clip(value)),
                None => println!("  text ({text_took:?}): none"),
            }
            println!(
                "  image ({image_took:?}): png {} bytes, tiff {} bytes",
                png.unwrap_or(0),
                tiff.unwrap_or(0)
            );
            println!();
        }
    }

    fn read_bytes(pasteboard: &NSPasteboard, kind: &NSString) -> Option<usize> {
        pasteboard.dataForType(kind).map(|data| data.len())
    }

    /// The interesting part of a type list is whether a marker is in it, not
    /// the dozen flavours an application offers the same content in.
    fn summarise(types: &[String]) -> String {
        if types.len() <= 4 {
            return types.join(", ");
        }
        format!("{}, and {} more", types[..4].join(", "), types.len() - 4)
    }

    fn clip(value: &str) -> String {
        let flat: String = value
            .chars()
            .map(|c| if c == '\n' { '⏎' } else { c })
            .collect();
        if flat.chars().count() <= 60 {
            flat
        } else {
            format!("{}…", flat.chars().take(60).collect::<String>())
        }
    }
}
