//! Does `clipboard-rs` see what the hand-rolled source sees?
//!
//! The decisive question is the concealed marker: if `available_formats` lists
//! the pasteboard types, the crate can do the privacy check and most of the
//! platform code stops being ours to maintain.

use clipboard_rs::common::RustImage;
use clipboard_rs::{
    Clipboard, ClipboardContext, ClipboardHandler, ClipboardWatcher, ClipboardWatcherContext,
};

struct Probe {
    ctx: ClipboardContext,
}

impl ClipboardHandler for Probe {
    fn on_clipboard_change(&mut self) {
        let formats = self.ctx.available_formats().unwrap_or_default();
        println!("change: formats = {formats:?}");
        let concealed = formats
            .iter()
            .any(|f| f.contains("ConcealedType") || f.contains("AutoGenerated"));
        println!("  concealed marker: {concealed}");
        match self.ctx.get_text() {
            Ok(text) => println!("  text: {:?}", text.chars().take(40).collect::<String>()),
            Err(_) => println!("  text: none"),
        }
        match self.ctx.get_image() {
            Ok(image) => println!("  image: {} png bytes", image.to_png().map(|p| p.get_bytes().len()).unwrap_or(0)),
            Err(_) => println!("  image: none"),
        }
        println!();
    }
}

fn main() {
    let probe = Probe {
        ctx: ClipboardContext::new().unwrap(),
    };
    let mut watcher = ClipboardWatcherContext::new().unwrap();
    watcher.add_handler(probe);
    println!("watching with clipboard-rs, ctrl-c to stop\n");
    watcher.start_watch();
}
